application/todo_list/urls.py
""" Module: urls as part of: todo_list

    Created by: Reinier on 22-10-2017. URL namespaces allow you to uniquely reverse named URL patterns even if
    different applications use the same URL names.

    Examples:
        Class-based views
            1. Add an import:  from other_app.views import Home
            2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
    TODO:
        - No topics for now.

"""
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.List.as_view(), name='index'),
    url(r'^page/(?P<page>\d+)/$', views.List.as_view(), name='page'),
    url(r'^detail/(?P<pk>\d+)/$', views.Detail.as_view(), name='detail'),
    url(r'^remove/(?P<pk>\d+)/$', views.Remove.as_view(), name='remove'),
    url(r'^create/$', views.Action.as_view(), name='create'),
]

system/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'', include('application.seennt.urls', namespace='seennt')),
    url(r'^auth/', include('utility.authenticate.urls', namespace='authenticate')),
    url(r'^todo-list/', include('application.todo_list.urls', namespace='todo-list')),
    url(r'^organize/', include('application.organize.urls', namespace='organize')),
    url(r'^share-score/', include('application.share_score.urls', namespace='share-score')),
    url(r'^admin/', admin.site.urls),
]

application/todo_list/models.py
# -*- coding: utf-8 -*-
""" Module: models as part of: todo_list

    Created by: Reinier on 22-10-2017. A model is the single, definitive source of information about your data.
    It contains the essential fields and behaviors of the data you’re storing. Generally, each model maps to a
    single database table.

    TODO:
        - Nothing for this moment.

"""
from django.db import models
from django.urls import reverse


# Create your models here.
class Action(models.Model):
    """: The class: "Action", is part of module: "models".

    A Action model to represent the database table Action. A action that needs to be done to fulfill a particular
    goal.

    Note:
        - Do not include the `self` parameter in the ``Args`` section.
        - The __init__ method is documented as a docstring on the __init__ method itself.
        - Class attributes, variables owned by the class itself. All values of class attributes are the same
          for each Instance.

    """
    #: description(CharField): Action description.
    description = models.CharField(max_length=200)

    #: subject(CharField): Action subject.
    subject = models.CharField(max_length=64)

    #: created(DateField): Creation date of action.
    created = models.DateField(auto_now_add=True)

    #: filed(DateField): Date when action is filed.
    filed = models.DateField(null=True)

    #: completed(BooleanField): Action is final.
    completed = models.BooleanField(default=0)


class Detail(models.Model):
    """: The class: "Detail", is part of module: "models".

    A Detail model to represent the database table Detail. details holds the steps that explains how a certain
    action is solved or what its actual status is.

    Note:
        - Do not include the `self` parameter in the ``Args`` section.
        - The __init__ method is documented as a docstring on the __init__ method itself.
        - Class attributes, variables owned by the class itself. All values of class attributes are the same
          for each Instance.

    """
    #: explanation(BooleanField): Step explained to fulfill action.
    explanation = models.CharField(max_length=200, null=True)

    #: edited(DateField): Date action adjusted.
    edited = models.DateField(auto_now_add=True)

    #: action(ForeignKey): Relation to action.
    action = models.ForeignKey(Action, on_delete=models.CASCADE)

application/todo_list/forms.py
from django.forms.models import inlineformset_factory, ModelForm
from application.todo_list import models


# Simplify the case of working with related objects via a foreign key.
# Create a formset that allows you to edit roadmaps belonging to a particular scenario.
class ActionForm(ModelForm):
    name = 'Todo action'

    class Meta:
        model = models.Action
        fields = ['description', 'subject']

ActionFormSet = inlineformset_factory(
    models.Action,
    models.Detail,
    fields=['explanation'],
    extra=1,
    can_delete=True,
)

application/todo_list/views.py
# -*- coding: utf-8 -*-
""" Module: views as part of: todo_list

    Created by: Reinier on 18-10-2017. Django appears to be a MVC framework, but you call the Controller the “view”,
    and the View the “template”. A view is a callable which takes a request and returns a response. This can be more
    than just a function, and Django provides an example of some classes which can be used as views.

    Examples:
        class AboutView(TemplateView):
            template_name = "about.html"

    TODO:
        - Use TODO comments for code that is temporary, a short-term solution, or good-enough but not perfect.

"""
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.core.urlresolvers import reverse_lazy
from django.views import generic
from application.todo_list import models, forms
from django.core.paginator import PageNotAnInteger, EmptyPage
from django.shortcuts import get_list_or_404, redirect
from facility.pagination import Pages
from django.contrib import messages


# Create your views here.
class List(LoginRequiredMixin, generic.ListView):
    """: The class: "List", is part of module: "views".

   Load the Action object to display.

    Note:
        - Do not include the `self` parameter in the ``Args`` section.
        - The __init__ method is documented as a docstring on the __init__ method itself.
        - Class attributes, variables owned by the class itself. All values of class attributes are the same
          for each Instance.

    """
    #: login_url(str): Login is required.
    login_url = 'authenticate:login'

    # redirect_field_name = 'todo-list:create'

    #: template_name(str): The page to display.
    template_name = 'todo_list/index.html'

    #: paginate_by(int): Amount of action objects to display.
    paginate_by = 10

    # Load the companies
    def get_queryset(self):
        """22-10-2017: The method: "get_queryset", is part of class: "List".

        The required objects are ordered by completed and date created.
        In addition a filter option based on subject is applicable. Initially it will load the default list and
        after setting a filter the list will be reduced.

        Returns:
            list: A list of object containing actions.

        """
        if 'filter' in self.request.GET:
            print('test')
            filter_val = self.request.GET.get('filter', None)
            actions = get_list_or_404(models.Action.objects.filter(subject=filter_val).order_by('completed', 'created'))
        else:
            actions = get_list_or_404(models.Action.objects.order_by('completed', 'created'))

        return actions

    def get_context_data(self, **kwargs):
        """22-10-2017: The method: "get_context_data", is part of class: "List".

        In addition to the list of action objects pagination and a unique action subject list should be available
        for our template system. To respectively divide the objects in pages and provide a unique list for our filter.

        Returns:
            list: A list of object containing actions.

        """
        context = super().get_context_data(**kwargs)
        context['fields'] = ['completed', 'created', 'description', 'subject', 'filed']

        try:
            page = int(self.kwargs['page'])
        except KeyError:
            page = 1

        # Set pagination for companies
        paginator = Pages(self.object_list, self.paginate_by)

        try:
            pages = paginator.page(page)
        except PageNotAnInteger:
            pages = paginator.page(1)
        except EmptyPage:
            pages = paginator.page(paginator.num_pages)

        # Hook function 'pages_to_show' to object 'pages'.
        setattr(pages, 'pages_to_show', paginator.pages_to_show(page))
        context['pages'] = pages

        context['unique_action_subject_list'] = models.Action.objects.distinct('subject')

        return context


class Action(LoginRequiredMixin, generic.CreateView):
    """: The class: "Action", is part of module: "views".

    Add a action to the database.

    Note:
        - Do not include the `self` parameter in the ``Args`` section.
        - The __init__ method is documented as a docstring on the __init__ method itself.
        - Class attributes, variables owned by the class itself. All values of class attributes are the same
          for each Instance.

    """
    #: login_url(str): Login is required.
    login_url = 'authenticate:login'

    #: model(object):A record of the table action.
    model = models.Action

    #: fields(list): List that contains the fields that needs to be added.
    fields = ['description', 'subject']

    def post(self, request, *args, **kwargs):
        """18-10-2017: The method: "post", is part of class: "Action".

        Handles POST requests, instantiating a form instance with the passed POST variables and then checked for
        validity. When a action is cancelled a redirect will be done.

        Args:
            request (list): Posted data.

        Returns:
            object: Posted action content.

        """
        if 'cancel' in self.request.POST:
            return redirect('todo-list:index')
        else:
            return super(Action, self).post(request, *args, **kwargs)

    def get_success_url(self):
        """18-10-2017: The method: "get_success_url", is part of class: "Action".

        get_success_url() is just providing somewhere to redirect to, which gets used in the default implementation of
        form_valid().

        Returns:
            str: Redirect to URL.

        """
        if 'add' in self.request.POST:
            messages.add_message(
                self.request,
                messages.INFO,
                'Action: "%s" is Added, please continue.' % self.request.POST.get('description')
            )
            return reverse_lazy('todo-list:create')
        elif 'return' in self.request.POST:
            messages.add_message(
                self.request,
                messages.SUCCESS,
                'Action: "%s" is listed.' % self.request.POST.get('description')
            )
            return reverse_lazy('todo-list:index')
        else:
            return reverse_lazy('todo-list:index')


class Detail(LoginRequiredMixin, SuccessMessageMixin, generic.UpdateView):
    """: The class: "Detail", is part of module: "views".

    Add a detailed information(Explanation) to action a certain action, and store this information in table detail.
    Explanation are provided via a formset/jquery.

    Note:
        - Do not include the `self` parameter in the ``Args`` section.
        - The __init__ method is documented as a docstring on the __init__ method itself.
        - Class attributes, variables owned by the class itself. All values of class attributes are the same
          for each Instance.

    """
    #: login_url(str): Login is required.
    login_url = 'authenticate:login'

    #: model(object):A record of the table action.
    model = models.Action

    #: success_url(str): URL to go to after successful removal.
    success_url = reverse_lazy('todo-list:index')

    #: success_message(str): A message displayed on the delete page conformation.
    success_message = 'Action: "%(description)s" is deleted.'

    #: template_name_suffix(str): The UpdateView page displayed. Eg. action_delete.html
    template_name_suffix = '_update'

    #: form_class(object): A object that holds the detailed form that should be displayed.
    form_class = forms.ActionForm

    def get_context_data(self, **kwargs):
        """18-10-2017: The method: "get_context_data", is part of class: "Action".

        Representing the template context. The keyword arguments provided will make up the returned context.

        Returns:
            dict: context data for displaying the object.

        """
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['formset'] = forms.ActionFormSet(self.request.POST, instance=self.object)
            context['formset'].full_clean()
        else:
            context['formset'] = forms.ActionFormSet(instance=self.object)
        return context

    def form_valid(self, form):
        """18-10-2017: The method: "form_valid", is part of class: "Action".

        This method is called when valid form data has been POSTed. It should return an HttpResponse.

        Args:
            form (object): Action form object to validate.

        Returns:
            str: Redirects to the success_url

        """
        context = self.get_context_data()
        formset = context['formset']
        if formset.is_valid():

            if 'completed' in self.request.POST:
                self.object.completed = True

                if self.request.POST['detail_set-0-explanation']:
                    self.object = form.save()
                    formset.instance = self.object
                    formset.save()
                    self.success_message = 'Action is completed!'
                    return super().form_valid(form)
                else:
                    messages.warning(self.request, 'Action can\'t be completed as there is no explanation given.')
                    return redirect(self.success_url)
            else:
                self.object = form.save()
                formset.instance = self.object
                formset.save()
                self.success_message = 'Action is updated, an explanation is added/removed or modified.'
                return super().form_valid(form)

        else:
            return self.render_to_response(self.get_context_data(form=form))


class Remove(LoginRequiredMixin, SuccessMessageMixin, generic.DeleteView):
    """: The class: "Remove", is part of module: "views".

    Remove a action from the database.

    Note:
        - Do not include the `self` parameter in the ``Args`` section.

application/todo_list/templates/todo_list/action_delete.html
{% extends 'todo_list/index.html' %}
{% load i18n static compress bootstrap3 %}

{% block content %}
{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

<legend>Are you sure you want to remove: {{ object.description }}?</legend>
<form action="." method="post" class="form" role="form">
  {% csrf_token %}
  {% buttons %}
        <button onclick="window.history.back();" class="btn btn-default" type="button">Cancel</button>
        <button type="submit" class="btn btn-primary">{% bootstrap_icon "trash" %} Remove</button>
  {% endbuttons %}
</form>
{% endblock %}

application/todo_list/templates/todo_list/action_form.html
{% extends 'todo_list/index.html' %}
{% load i18n static compress bootstrap3 %}

{% block content %}
{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}
{# Form errors #}
{% bootstrap_form_errors form %}

<form class="form" role="form" action="." method="post">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
    <button type="submit" formnovalidate class="btn btn-default" name="cancel" value="Cancel">Cancel</button>
    <button type="submit" class="btn btn-primary" name="add">{% bootstrap_icon "plus" %} Save & Continue</button>
    <button type="submit" class="btn btn-primary" name="return">{% bootstrap_icon "star" %} Save & Return</button>
  {% endbuttons %}
</form>
{% endblock %}

application/todo_list/templates/todo_list/action_update.html
{% extends 'todo_list/index.html' %}
{% load i18n register static compress bootstrap3 %}

{% block content %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}
{# Form errors #}
{% bootstrap_form_errors form %}

    <form class="form" role="form" action="." method="post">
    {%  csrf_token %}
    {% if form %}
        <legend>{{ form.name|upper }}</legend>
        {% bootstrap_form form layout="vertical" %}
    {% endif %}

    {% if formset %}
    <div class="controls">
    <div class="prefix" id="{{ formset.prefix }}"></div>
    <legend>{{ formset.model| model_name | upper }}</legend>
    {{ formset.management_form }}
    {% for form in formset.forms %}
            <div class="entry form-group">
                {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                {% endfor %}
                <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">
                    {% if form.instance.edited %}{{ form.instance.edited|date:'d-m-Y' }}{% else %}{% now "d-m-Y" %}{% endif %}
                </span>
                <input type="text" name="{{ form.explanation.html_name }}"
                       id="{{ form.explanation.auto_id }}" class="form-control"
                       placeholder="Explain..."
                       {% if form.explanation.value != None %}value="{{ form.explanation.value }}{% endif %}">
                <span class="input-group-btn">
                    {% if forloop.last %}
                        <button class="btn btn-default btn-add"  type="button"><span class="glyphicon glyphicon-plus"></span></button>
                    {% else %}
                        <button class="btn btn-default btn-remove"  type="button"><span class="glyphicon glyphicon-minus"></span></button>
                    {% endif %}
                </span>
                </div><!-- /input-group -->
            </div>

    {% endfor %}
    </div>
    {% endif %}

    <div class="form-group">
        <button onclick="window.history.back();" class="btn btn-default" type="button">Cancel</button>
        <button type="submit" class="btn btn-primary" value="1" name="completed">{% bootstrap_icon "star" %} Save & Complete</button>
        <button type="submit" class="btn btn-primary" name="return">{% bootstrap_icon "plus" %} Save & Return</button>
    </div>
    </form>

{% endblock %}

application/todo_list/templates/todo_list/content.html
{% load i18n bootstrap3 staticfiles compress %}
{% block content %}
{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

    <div class="row">

                <div class="col-xs-7 col-sm-5 col-md-3 col-lg-3 col-md-offset-7 col-sm-offset-5 col-xs-offset-0 col-lg-offset-7">
                <form method="get" action="{% url 'todo-list:index' %}">
                    <select name="filter" id="filter" class="form-control" onchange="this.form.submit()">
                        <option value="#">Select a subject...</option>
                        {% for subject in unique_action_subject_list %}
                            <option value="{{ subject.subject }}">{{ subject.subject }}</option>
                        {% endfor %}
                    </select>
                </form>
                </div>
                <div class="col-xs-3 col-sm-2 col-md-2 col-lg-2 col-md-offset-0 col-sm-offset-0 col-xs-offset-2 col-lg-offset-0">
                <form action="{% url 'todo-list:create' %}">
                    {% bootstrap_button 'Add new action' button_type='submit' button_class='btn btn-primary pull-right' %}
                </form>
                </div>
        </div>

    <div class="row">
        <table class="table table-hover">
    <thead>
    <tr>
        {% for field in fields %}
            {% if forloop.first %}
                <th class="text-center">{{ field | upper }}</th>
            {% else %}
                <th>{{ field | upper }}</th>
            {% endif %}
        {% endfor %}
        <th>ARCHIVE</th>
    </tr>
    </thead>
    {% for action in object_list %}
        <tr class='clickable-row' data-href="{% url 'todo-list:detail' action.id %}">
            <td class="text-center">
                {% if action.completed %}
                    <span class="glyphicon glyphicon-ok"></span>
                {% else %}
                    <span class="glyphicon glyphicon-remove"></span>
                {% endif %}
            </td>
            <td>{{ action.created }}</td>
            <td>{{ action.description }}</td>
            <td>{{ action.subject }}</td>
            <td>{{ action.filed }}</td>
            <td class="text-center">
                <a href="{% url 'todo-list:remove' action.id %}"><span class="glyphicon glyphicon-trash"></span></a>
            </td>
        </tr>
    {% endfor %}
    </table>

    {% if is_paginated %}
        <div class="text-center">
            <ul class="pagination pagination-md">
        {% if pages.has_previous %}
        <li>
            <a href="{% url 'todo-list:page' pages.previous_page_number  %}" aria-label="Next">
                <span aria-hidden="true" class="glyphicon glyphicon-chevron-left"></span>
            </a>
        </li>
        {% endif %}
        {% for page in pages.pages_to_show %}
              {% if page == -1 %}
                  <li class="disabled">
                      <a href="#">
                          <span class="glyphicon glyphicon-option-horizontal"></span>
                      </a>
                  </li>
              {% elif page == pages.number %}
                <li class="{% if pages.number == page  %}active{% endif %}">
                    <a href="{% url 'todo-list:page' page %}">{{ page }}</a>
                </li>
              {% else %}
                <li>
                    <a href="{% url 'todo-list:page' page %}">{{ page }}</a>
                </li>
              {% endif %}
        {% endfor %}
        {% if pages.has_next %}
        <li>
            <a href="{% url 'todo-list:page' pages.next_page_number  %}" aria-label="Next">
                <span aria-hidden="true" class="glyphicon glyphicon-chevron-right"></span>
            </a>
        </li>
        {% endif %}
    </ul>
        </div>
    {% endif %}
    </div>

{% endblock %}

application/todo_list/templates/todo_list/header.html
{% load i18n bootstrap3 static compress %}

{## Here we override the project navbar. #}
{% block navbar %}
{% include 'todo_list/snippets/navbar.html' %}
{% endblock %}

application/todo_list/templates/todo_list/index.html
{% extends 'base.html' %}
{% load compress static i18n bootstrap3 %}

<!-- META html meta data -->
{% block meta %}
{% include 'todo_list/meta.html' %}
{% endblock %}

<!-- CSS external style sheets -->
{% block style %}
{% include 'todo_list/style.html' %}
{% endblock %}

<!-- JS/JQUERY external scripts -->
{% block script %}
{% include 'todo_list/script.html' %}
{% endblock %}

{% block header %}
{% include 'todo_list/header.html' %}
{% endblock %}

{% block content %}
    <div class="container">
    {% include 'todo_list/content.html' %}
    </div>
{% endblock %}

{% block footer %}
{% include 'todo_list/footer.html' %}
{% endblock %}

application/todo_list/templates/todo_list/navbar.html
{% load i18n bootstrap3 static compress %}
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <!-- NAVIGATION Display menu items -->
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-ex1-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

        <a class="navbar-brand" href="/">
            <span><img src="{% static "img/logo.png" %}" width="50" class="img-circle" alt="Company logo"></span>
            seennt
        </a>

        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-right" id="navbar-ex1-collapse">
            {% include 'snippets/navbar_links.html' %}
        </div><!-- /.navbar-collapse -->
    </div>
</nav>

application/todo_list/templates/todo_list/script.html
{% load static i18n %}
{% block script %}
    <script src="{% static 'js/clickable.js' %}"></script>
    <script src="{% static 'js/dynamic-formset.js' %}"></script>
{% endblock %}

application/todo_list/templates/todo_list/style.html
{% load i18n bootstrap3 static compress %}

{% compress css %}
<link rel="stylesheet" type="text/x-scss" href="{% static "scss/todo_list.scss" %}" />
<link rel="stylesheet" type="text/css" href="{% static "css/custom.css" %}" />
{% endcompress %}