application/seennt/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView


urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name="seennt/index.html"), name='index'),
]

system/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'', include('application.seennt.urls', namespace='seennt')),
    url(r'^auth/', include('utility.authenticate.urls', namespace='authenticate')),
    url(r'^todo-list/', include('application.todo_list.urls', namespace='todo-list')),
    url(r'^organize/', include('application.organize.urls', namespace='organize')),
    url(r'^share-score/', include('application.share_score.urls', namespace='share-score')),
    url(r'^admin/', admin.site.urls),
]

utility/authenticate/urls.py
from django.conf.urls import url
from django.contrib.auth import views

urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(template_name="authenticate/login.html"), name='login'),
    url(r'^logout/$', views.LogoutView.as_view(template_name="authenticate/logout.html"), name='logout'),

    # url(r'^password_change/$', views.PasswordChangeView.as_view(), name='password_change'),
    # url(r'^password_change/done/$', views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    #
    # url(r'^password_reset/$', views.PasswordResetView.as_view(), name='password_reset'),
    # url(r'^password_reset/done/$', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    # url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    #     views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # url(r'^reset/done/$', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

utility/authenticate/models.py
from django.db import models

# Create your models here.

utility/authenticate/views.py
from django.shortcuts import render


# Create your views here.

utility/authenticate/templates/authenticate/content.html
{% extends 'authenticate/index.html' %}
{% load i18n bootstrap3 staticfiles compress %}

{% block content %}
{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{% endblock %}

utility/authenticate/templates/authenticate/header.html
{% load i18n bootstrap3 static compress %}

{% block navbar %}
{% include 'authenticate/navbar.html' %}
{% endblock %}

{% block jumbotron %}

{% endblock %}

utility/authenticate/templates/authenticate/index.html
{% extends 'base.html' %}
{% load compress static i18n bootstrap3 %}

<!-- META html meta data -->
{% block meta %}
{% include 'authenticate/meta.html' %}
{% endblock %}

<!-- CSS external style sheets -->
{% block style %}
{% include 'authenticate/style.html' %}
{% endblock %}

<!-- JS/JQUERY external scripts -->
{% block script %}
{% include 'authenticate/script.html' %}
{% endblock %}

{% block header %}
{% include 'authenticate/header.html' %}
{% endblock %}

{% block content %}
{% include 'authenticate/content.html' %}
{% endblock %}

{% block footer %}
{% include 'authenticate/footer.html' %}
{% endblock %}

utility/authenticate/templates/authenticate/login.html
{% extends 'authenticate/content.html' %}
{% load i18n bootstrap3 staticfiles compress %}
{% block content %}
{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

    <div class="container">
        <div class="row">
            <div class="col-sm-6 col-md-6 col-lg-6 col-md-offset-3 col-sm-offset-3 col-lg-offset-3">

            <div class="panel panel-default">
                <div class="panel-body">
                    <form action="{% url 'authenticate:login' %}" method="post" role="form">
                        {% csrf_token %}
                        <legend>Welcome back! Please login?</legend>

                        <div class="form-group">
                            {{ form.username.html_name|capfirst }}
                            <input type="text" name="{{ form.username.html_name }}" id="{{ form.username.auto_id }}" class="form-control" placeholder="Username...">
                        </div>

                        <div class="form-group">
                            {{ form.password.html_name|capfirst }}
                            <input type="password" name="{{ form.password.name }}" id="{{ form.password.id }}" class="form-control" placeholder="Password...">
                        </div>

                        <button type="submit" class="btn btn-primary">Login</button>
                        <input type="hidden" name="next" value="{{ next }}" />
                    </form>
                </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

utility/authenticate/templates/authenticate/logout.html
{% extends 'authenticate/content.html' %}
{% load i18n bootstrap3 staticfiles compress %}
{% block content %}
{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

    <div class="container">
        <div class="row">
            <div class="col-sm-6 col-md-6 col-lg-6 col-md-offset-3 col-sm-offset-3 col-lg-offset-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <legend>You are logged out.</legend>
                        <a href="{% url 'seennt:index' %}">Return to homepage</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}